# Generated by Django 2.2.3 on 2019-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LampPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False, verbose_name='Power is on')),
                ('brightness', models.IntegerField(default=0, max_length=3, verbose_name='brightness percent')),
                ('on_time', models.DateTimeField(blank=True, verbose_name='Time the power on')),
                ('off_time', models.DateTimeField(blank=True, verbose_name='Time the power off')),
            ],
        ),
    ]
