# Generated by Django 2.2.3 on 2019-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamppost',
            name='lamp_id',
            field=models.IntegerField(default=1, verbose_name='Lamp number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lamppost',
            name='brightness',
            field=models.IntegerField(default=0, verbose_name='brightness percent'),
        ),
    ]
