# Generated by Django 2.2.3 on 2019-08-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190801_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamppost',
            name='off_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time the power off'),
        ),
        migrations.AlterField(
            model_name='lamppost',
            name='on_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time the power on'),
        ),
    ]
