# Generated by Django 2.2.3 on 2019-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190801_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamppost',
            name='brightness',
            field=models.IntegerField(default=50, verbose_name='brightness percent'),
        ),
        migrations.AlterField(
            model_name='lamppost',
            name='is_on',
            field=models.IntegerField(choices=[(1, 'ON'), (0, 'OFF')], default=0, verbose_name='Power'),
        ),
        migrations.AlterField(
            model_name='lamppost',
            name='lamp_id',
            field=models.IntegerField(unique=True, verbose_name='Lamp number'),
        ),
    ]
